apiVersion: v1
kind: Namespace
metadata:
  name: first-complete-kubernetes-project
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: first-complete-kubernetes-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "admin123"
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: first-complete-kubernetes-project
spec:
  capacity:
    storage: 5Gi  # Change this as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mongodb  # This is for testing. Use a proper storage solution for production
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: first-complete-kubernetes-project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Change this as needed
  storageClassName: ""  # Leave blank if using a static PV like above
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: first-complete-kubernetes-project
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30100
  type: NodePort
